example/1_basic.html
example/2_features.html
js/jsmind.js

now, you can customize background color and foreground color for a node by 3 ways below:
```javascript
var mind = {
... 
// define in mind data
{"id":"sub1", "parentid":"root", "topic":"sub1", "background-color":"#0000ff", "foreground-color":"black"},
...
}
```
```javascript
// or when you create a node 
jm.add_node("sub2","sub23", "new node", {"background-color":"red"});
```
```javascript
// or at any time
jm.set_node_color('sub21', 'green', '#ccc');
```

support custom style : background-color and foreground-color	

---

js/jsmind.draggable.js

When use with a touch device, drag a node should not scroll the canvas.
If a node is not beeing dragged, scroll works as usual.

Prevent scroll when dragging a node

---

js/jsmind.draggable.js
js/jsmind.js
js/jsmind.screenshot.js

The change is also applied to drag and screenshot features.
The angle is set as a number. Tested with 0, 90, 180 and 270 degrees.

Add a method to enable rotate the background in a image node

---

js/jsmind.js

通过将功能键分配到 1000以上的数字来实现简单的组合按键方式，之所以采用这种方式而没有采用组合keyCode为字符串的形式是为了尽可能的不改变原有的逻辑。

add 简单支持组合按键事件

---

js/jsmind.js

In the Mindmap-Tool Xmind the Tab key is used to create child nodes. When i want to use tab in jsmind the browser change focus after first tab.
This fix allow you tu usse the tab key for any operation

prevent tab to change focus in browser

---

js/jsmind.js

修复在使用svg的报错：Cannot assign to read only property 'className' of object '[object SVGSVGElement]'

修改svg的class的赋值方式

---

docs/en/2.options.md
js/jsmind.js

Adding "draggable" option and corresponding "_drag_nodes" function, to override default behavior in case the mind map is bigger than the container.
If true, no vertical nor horizontal scrollbars will appear, instead the whole mind map will be draggable while mouse button is down.

Draggable option (hizzgdev#323)

---

style/jsmind.css

bug fix #364 :
given `position: absolute` to the  screenshot `canvas`, so that it won't inflate the parent element.

hide screenshot canvas, resolve #364

---

js/jsmind.js
package-lock.json
package.json
src/jsmind.common.js
src/jsmind.js

allow to use `'left'`/`'right'` on `add_node`/`insert_node_before`/`insert_node_after`. So they will be all right
```
jm.add_node(node, id, topic, {}, 'left')
jm.add_node(node, id, topic, {}, jsMind.direction.left)
jm.add_node(node, id, topic, {}, -1)
```
resolve https://github.com/hizzgdev/jsmind/issues/426
the feature is included in 0.5.4

[Feature] allow string direction

---

src/jsmind.view_provider.js

The dom event is not required by `zoom` function now.
The mindmap will zoom with mindmap center as the zoom center by default.

allow zoom mindmap out of mouse event handler

---

docs/en/2.options.md
docs/zh/2.options.md
src/jsmind.graph.js
src/jsmind.js
src/jsmind.option.js

Add a new option `view.line_style` to control the style of mindmap lines.
| line_style = 'curved' | line_style = 'straight' |
| -- | -- |
| <img width="1000" alt="image" src="https://github.com/hizzgdev/jsmind/assets/1690290/36ec94d5-0ddc-4daa-a64f-9be16a3dd97c"> | <img width="1001" alt="image" src="https://github.com/hizzgdev/jsmind/assets/1690290/1f555afc-9e08-469a-b2eb-2cb5718c006b"> |

[Feature] new option of line style

---

README.md
example/1_basic.html
example/1_basic_cn.html
example/3_requirejs.html
package-lock.json
package.json
src/jsmind.common.js

Add demo with requirejs.
Update version to v0.6.5

[Doc] add demo with requirejs, update to v0.6.5

---

src/plugins/jsmind.draggable-node.js

It's found that, the double-click event is broken by the `this.capture = true` in the `draggabe-node` plugin, in specific versions of OS and browsers.
Resolve https://github.com/hizzgdev/jsmind/issues/471 .

fix bug: draggable-node plugin block dblclick to trigger the edit mode

---

src/plugins/jsmind.draggable-node.js

Since the root cause is the unexpected `mousemove` event, we can add a condition to avoid it instead of delay trigger (https://github.com/hizzgdev/jsmind/pull/511).

re-fix bug: draggalbe-node plugin block double click unexpected

---

src/plugins/jsmind.draggable-node.js

It's found that `drag_start` is called on right click, this PR avoid the behavior.

dragging is only triggered when the left button is pressed

---

src/plugins/jsmind.draggable-node.js

Add `hovered node` to help lock the target node

optimize the logic of looking up the target node

---

src/plugins/jsmind.draggable-node.js

optimize: draggable-node
1. add condition to reduct the calculation on lookup target node
2. fix bug that it won't trigger `drag` when mouse move to left and/or up
3. rename the method in the plugin

don't lookup node when the node is not moved, and fix bug on mousemove

---

src/jsmind.js
src/jsmind.option.js
src/jsmind.view_provider.js

Add new option `custom_node_render` to support vary rendering logic.
Now, It's possible to customize your rendering logic for specific node.
```javascript
let options = {
...
view: {
custom_node_render: function (jm, element, node) {
// any customized logic
let updatedTopic = '<img src="">'+node.topic;
element.innerHTML = updatedTopic;
// return true to tell jsMind the node has been rendered
return true;
}
}
}
```

add new option custom_node_render to support vary rendering logic

---

docs/en/2.options.md
docs/zh/2.options.md

add docs for the new options `view.zoom` and `view.custom_node_render`.

[docs] update docs for the new options

---

README.md
docs/en/1.usage.md
docs/en/plugin-screenshot.md
docs/zh/1.usage.md
docs/zh/plugin-screenshot.md
example/1_basic.html
example/1_basic_cn.html
example/2_features.html
example/2_features_cn.html
example/3_requirejs.html
package-lock.json
package.json
src/jsmind.common.js

upgrade to 0.7.7

---

docs/en/2.options.md
docs/zh/2.options.md

Doc for https://github.com/hizzgdev/jsmind/pull/545

[Doc] add doc for new option view.expander_style

---

src/plugins/jsmind.screenshot.js

An issue has been confirmed where the screenshot feature is broken when zooming. which is reported in https://github.com/hizzgdev/jsmind/issues/552.
This PR fix the issue, and will resolve #552.

[Bugfix] fix bug that the screenshot is broken when jsmind is zoomed

---

src/jsmind.mind.js

An issue has been confirmed where the `find_node_after` and `find_node_before` works unexpected after nodes are removed, which is reported in https://github.com/hizzgdev/jsmind/issues/551.
The api `find_node_after` and `find_node_before` relies on the continuity of `index` field of nodes. But the index of nodes are not updated after nodes are removed.
This PR update the nodes' index, and resolve #551.

[Bugfix] update index after remove node

---

src/jsmind.view_provider.js

It's confirmed that `zoom` doesn't work when `zoom < 1` and the container is changed bigger.
This PR fix the bug. It's a very small fix, will be included in the next version.

[Bugfix] zoom doesn't work when zoom < 1 and container size is changed bigger

---

src/plugins/jsmind.draggable-node.js

When a node is rendered by `custom_node_render`, and additional html element is added to the node, the node probably can not be dragged, because the target of the event is not `<jmnode...>` 
Fix https://github.com/hizzgdev/jsmind/issues/566 .

fix bug that customized node can not be dragged

---

src/jsmind.mind.js

An [issue 584](https://github.com/hizzgdev/jsmind/issues/584) has been confirmed that moving node up/down works unexpected after node is moved to other parent.
The root cause is same as https://github.com/hizzgdev/jsmind/pull/554, and the indexes of nodes in the original parent are not updated.
This PR update the nodes' index, and resolve the issue https://github.com/hizzgdev/jsmind/issues/584.

[Bugfix] update index after node is moved to other parent

---

docs/en/2.options.md
docs/zh/2.options.md
src/jsmind.graph.js
src/jsmind.js

Line style controlled by user.
Replace `line_style` option with a function to draw a custom line.
docs in this PR.

[Feature] configure custom line-drawing method

---

src/jsmind.js

当刷新或者显示脑图时可以自行选择是否居中
refresh jsmind can set to center or not.

feat: refresh jsmind can set to center or not

---

src/plugins/jsmind.draggable-node.js

It's reported by https://github.com/hizzgdev/jsmind/issues/622 that the editing node can be dragged, and the input element is included in the node instead of the node topic.
Actually a node in editing should not be dragged, because users are editing the content, the dragging probably be a misoperation. This PR disable the dragging while editing.

fix bug: the editing node can be dragged
