hizzgdev/jsmind

js/jsmind.draggable.js
Drag nodes didn't work with touch devices.
=> Add support for touch events

example/2_features.html, js/jsmind.js
Use transform scale instead of zoom, have better compatibility and solves the hiding of toggle circles
=> Zoom feature

js/jsmind.js
=> 添加全部收起节点函数,实现所有子节点都收起,jm.collapse_all()

js/jsmind.js
When use set_theme() function, get this error.
Great tool ;-)
=> Fix ReferenceError: assignment to undeclared variable nodeid

js/jsmind.js, package.json
fixed a problem "no package.json" while I try to use "npm install“，exports jm for using.
now it works ok.
=> fixed add npm to jsmind

js/jsmind.js
这个是修改前的bug演示：https://jsfiddle.net/linzb93/fs4fnj64/
=> 修复和jQuery的toggleClass方法配合使用时根节点类名错乱的问题

js/jsmind.screenshot.js
modified:   js/jsmind.screenshot.js
=> fixed the watermark could not be rendered in shootDowndown().

js/jsmind.js, style/jsmind.css
doing one change for my own purpose, structured data on update node events, and add some more events requested by someone else.
Hope this help.
=> more event generated, update node structured data, per node read only setting,  canvas and svg specific css.

docs/en/2.options.md, js/jsmind.js
translate the options-documentation to english
=> English options translation

js/jsmind.js
insert_node_after  参数获取错误， 添加时会报错
=> insert_node_after  参数获取错误。

docs/en/1.usage.md, docs/en/2.options.md, docs/en/3.operation.md, docs/en/4.contribution.md, docs/en/index.md
also add the last part of translation and fix a markup-error (sorry)
=> Update whole english translation

js/jsmind.js
修复:因mode兼容引起的direction错误导致drag不能正确检测的问题,代码 jsmind.js 238行
=> 修复:因mode兼容引起的direction错误导致drag不能正确检测的问题

js/jsmind.js, tests/jsmind.mind.test.js
- refactor mind.move_node use node instead node_id
- add unit test for mind.move_node
=> [refactor]refactor mind.move_node, and add unit tests for it

js/jsmind.js, tests/jsmind.mind.test.js
- refactor mind.remove_node
- add unit test for mind.remove_node
=> refactor mind.remove_node, and add ut for it

tests/unit/jsmind.dom.test.js, tests/unit/jsmind.format.test.js
Add unit test for jsmind.dom.js & jsmind.format.js
=> add test for jsmind.dom & jsmind.format

tests/unit/jsmind.data_provider.test.js, tests/unit/jsmind.format.test.js, tests/unit/jsmind.graph.test.js
Add unit test for jsmind.graph.js
=> add unit test for graph module

tests/unit/jsmind.node.test.js
=> add unit test for node module

package-lock.json, package.json
Add local server support. Now, we call start a a simple static http server on local with command:
```
npm run server
```
=> add local server support

README.md
There are some issues on it, so we just remove the demo link for now.
=> remove mathjax demo link

js/jsmind.js
=> fix zoom position

.config/rollup.config.js, LICENSE, js/jsmind.draggable-node.js, js/jsmind.js, js/jsmind.screenshot.js, src/jsmind.common.js, src/jsmind.data_provider.js, src/jsmind.dom.js, src/jsmind.format.js, src/jsmind.graph.js, src/jsmind.js, src/jsmind.layout_provider.js, src/jsmind.mind.js, src/jsmind.node.js, src/jsmind.option.js, src/jsmind.plugin.js, src/jsmind.shortcut_provider.js, src/jsmind.util.js, src/jsmind.view_provider.js, src/plugins/jsmind.draggable-node.js, src/plugins/jsmind.screenshot.js, style/jsmind.css
=> copyright-2023

docs/en/2.options.md, docs/zh/2.options.md, js/jsmind.js, package-lock.json, package.json, src/jsmind.js, src/jsmind.option.js, src/jsmind.view_provider.js, style/jsmind.css
A new option `view.node_overflow` is added by this PR, with which we can control the text overflow style. There are 2 optional value for it:
1. `hidden` (default) : the overflowed text will be hidden
2. `wrap` : the overflowed text will be wrapped, so a node may become multi-lines.
| node_overflow = wrap | node_overflow = hidden |
| --- | --- |
| <img width="624" alt="image" src="https://user-images.githubusercontent.com/1690290/226505125-88c3ef4f-bb51-4fc6-8162-8445d75cb92b.png"> | <img width="587" alt="image" src="https://user-images.githubusercontent.com/1690290/226505272-0683bb26-1db5-4f19-b65d-c9e7d23f543a.png"> |
=> [Feature] add new option node_overflow to allow to wrap the text in a node

docs/en/1.usage.md, docs/zh/1.usage.md
Update doc to avoid misunderstanding about data format
=> [Doc] avoid misunderstanding about data format

README.md, docs/en/1.usage.md, docs/zh/1.usage.md, example/1_basic.html, example/2_features.html, example/2_features_es6.html
=> [Docs] change default cdn

example/1_basic.html, example/2_features.html, example/2_features_es6.html, example/3_mathjax.html, example/demo.html, js/jsmind.js, src/jsmind.js
Add warning to the static method `jsMind.show`, remove the reference of `jsMind.show` from all the demo html pages.
=> [Quality] do not use the static method jsmind.show

js/jsmind.draggable-node.js, src/plugins/jsmind.draggable-node.js
scrolling container axisX if drag nodes exceeding container #433
=> [Features] allow scroll container if drag node exceeding viewport

js/jsmind.draggable-node.js, src/plugins/jsmind.draggable-node.js
- Add new option `line_color` to customize the line;
- Extract options to customize the behavior of the new feature added in #450  cc @Niubility-SunLight
=> [Refactor] refactor the options in plugin draggable-node

js/jsmind.js, src/jsmind.js, src/jsmind.view_provider.js, tests/unit/jsmind.test.js
Fix bug that the html node can not be selected, Resolve #455
=> [Bugfix] fix bug that the html node can not be selected

package-lock.json, package.json
=> update version to 0.5.6

README.md, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html
- Change resource url in demo to `jsdelivr` CDN
- Add new demo pages using China CDN
=> [Demo] change cdn url, add demo pages using cdn mirror in China

js/jsmind.js, package.json, src/jsmind.common.js
It's probably the last js version of jsMind. The next version will be ES6 version.
=> update npm version to 0.5.7

package-lock.json, src/jsmind.common.js
=> update version to 0.6.0

package-lock.json, package.json, src/jsmind.common.js, src/jsmind.js, src/jsmind.option.js, src/jsmind.view_provider.js
Now, jsMind will zoom with mouse position as the center point.
Resolve #440 
Resolve #462 
Update version to 0.6.1
=> [optimization] zoom with mouse position as the center point

package-lock.json, package.json, src/jsmind.common.js
=> update version to 0.6.2

src/jsmind.js, src/jsmind.option.js, src/jsmind.view_provider.js
- optimize zoom method to avoid zoom_out much
- revert default option of `vmargin` and `hmargin`
=> [Optimize] optimize zoom method to avoid zoom_out much

example/2_features.html, src/jsmind.js, src/jsmind.option.js, src/plugins/jsmind.draggable-node.js
move options of plugin to `plugin` field of options.
=> [Feature] relocate options of plugin

package-lock.json, package.json, src/jsmind.common.js
=> upgrade npm version to 0.6.3

README.md, docs/en/1.usage.md, package-lock.json, src/jsmind.common.js
=> update version to 0.6.4

.config/rollup.config.js, package.json, src/plugins/jsmind.draggable-node.js, src/plugins/jsmind.screenshot.js
Setup dependencies in plugins [draggable-node, screenshot]. So the package management framework will handle the relationship between libs.
E.g.
```
require(['jsmind', 'jsmind/draggable-node'], function (jsMind, _) {
load_jsmind(jsMind);
});
```
=> [Optimize] setup dependencies in plugins

package-lock.json, package.json, src/jsmind.common.js
=> update version to 0.6.5-preview

README.md, docs/en/1.usage.md, docs/zh/1.usage.md, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [RELEASE] update version to 0.7.0

.config/rollup.config.js, example/2_features.html, example/2_features.js, example/2_features_cn.html, src/jsmind.plugin.js, src/plugins/jsmind.screenshot.js
Refactor jsmind plugin screenshot.
=> [Refactor] refactor screenshot

README.md, docs/en/1.usage.md, docs/en/experimental-features.md, docs/zh/1.usage.md, docs/zh/experimental-features.md, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> upgrade to v0.7.3

README.md, docs/en/1.usage.md, docs/en/experimental-features.md, docs/zh/1.usage.md, docs/zh/experimental-features.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> upgrade to 0.7.4

src/plugins/jsmind.draggable-node.js
- Search for overlapping nodes to improve performance of finding nearest nodes
- Remove outdated `event` reference
- Make lines appear in a special color when movement is invalid
=> [plugin][draggable-node] remove outdated event

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> update version to 0.7.5

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> update version to 0.7.6

src/jsmind.view_provider.js, tests/unit/jsmind.test.js
Support to show mind in the hidden container to avoid the situation reported in https://gitee.com/hizzgdev/jsmind/issues/I8K3MR
=> [Feature] enable show mind in the hidden container

example/demo.html, src/jsmind.js, src/jsmind.option.js, src/jsmind.view_provider.js, style/jsmind.css
Add new option `view.expander_style` to show number in expander.
| default style | number style |
| --- | --- |
| ` view: { expander_style : 'char' } `| `view: { expander_style : 'number' }`|
| <img width="469" alt="image" src="https://github.com/hizzgdev/jsmind/assets/1690290/8462da63-3c1f-4858-9f66-e088670115e2"> | <img width="396" alt="image" src="https://github.com/hizzgdev/jsmind/assets/1690290/e309e397-dbf5-424d-a0be-32ab99a902d2"> |
=> [Feature] add option to show number in expander

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] upgrade version to 0.7.8

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> upgrade to 0.7.9

src/jsmind.format.js, src/jsmind.util.js
- Remove outdated util method `ajax`
- Update the example in different data formats
=> [Refactor] remove outdated ajax method, update the example data in different formats

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] update version to 0.8.0

src/plugins/jsmind.screenshot.js
New option to control the background color of the exported image.
discussion: https://github.com/hizzgdev/jsmind/discussions/574
=> [Feature] add option to control the background color of the exported image

src/jsmind.format.js, tests/unit/jsmind.format.test.js
Support `folded` field in [freemind schema](https://freemind.sourceforge.io/wiki/index.php/File_format)
Discussion : #575 , Thanks @harlan3
=> [Bugfix] support folded field in freemind

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> upgrade jsmind to 0.8.2

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] upgrade version to 0.8.3

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] upgrade version to 0.8.4

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] upgrade version to 0.8.5

.config/rollup.config.js, package-lock.json, package.json
Fix https://github.com/hizzgdev/jsmind/security/dependabot/16
=> upgrade rollup

src/jsmind.layout_provider.js
=> fixup the bug that cousin space doesn't take effect on 1-child-node

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] new version 0.8.6

.vscode/project-words.txt, src/jsmind.format.js, tests/unit/jsmind.format.test.js
update `COLOR` and `BACKGROUND_COLOR` attributes in freemind format according to [freemind schema](https://freemind.sourceforge.io/wiki/index.php/Freemind.xsd)
Resolve https://github.com/hizzgdev/jsmind/issues/630
Thanks @opto
=> update color and background_color according to the schema of freemind

src/jsmind.js, src/jsmind.option.js
update of https://github.com/hizzgdev/jsmind/pull/629
@smonsarr
=> [Features] Scenari mouse zoom

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> [Release] update version to 0.8.7

README.md, docs/en/1.usage.md, docs/en/plugin-screenshot.md, docs/zh/1.usage.md, docs/zh/plugin-screenshot.md, example/1_basic.html, example/1_basic_cn.html, example/2_features.html, example/2_features_cn.html, example/3_requirejs.html, package-lock.json, package.json, src/jsmind.common.js
=> update version to 0.9.0
